### ISSUE TITLE
Failed to parse .csv file

### ISSUE THREAD

**Issue by chouzee** [leapcell/leapcell-py#1]
Hi! First, I'm unsure if it's the right place to raise an issue related to uploading .csv files. I've tried to upload a file that has 4k rows. I have read the document about database, but didn't find any mention of file size or row size. Could you clarify if there is some kind of limitations?

**Comment by issac0v0** [comment]
Currently, 4k is allowed, needs to be less than 50k, because the loading speed is relatively slow.

**Comment by issac0v0** [comment]
Why don't you give it another try?

**Comment by chouzee** [comment]
Sorry, the issue was on my side. I'm closing this one and thank you for your feedback
